---@meta

--[[
  Exported in src\xrGame\script_game_object_script.cpp

  game_object methods are defined here:
    * src\xrGame\script_game_object_script_trader.cpp
    * src\xrGame\script_game_object_script2.cpp
    * src\xrGame\script_game_object_script3.cpp
]]--


---@class CSightParams
---@field m_object any
---@field m_vector any
---@field m_sight_type any
CSightParams = {}

-- Exported has bla-bla in source code
---@enum CSightParams.bla_bla
CSightParams.bla_bla = {}

---@class game_object
---@field health any
---@field psy_health any
---@field power any
---@field satiety any
---@field radiation any
---@field morale any
---@field bleeding any
game_object = {}

function game_object:set_trader_global_anim() end
function game_object:set_trader_head_anim() end
function game_object:set_trader_sound() end
function game_object:external_sound_start() end
function game_object:external_sound_stop() end

-- Following method are defined here: src\xrGame\script_game_object_script2.cpp
function game_object:change_health() end
function game_object:change_psy_health() end
function game_object:change_power() end
function game_object:change_satiety() end
function game_object:change_radiation() end
function game_object:change_morale() end
function game_object:get_bleeding() end
function game_object:xform() end
function game_object:bounding_box() end
function game_object:center() end
function game_object:position() end
function game_object:direction() end
function game_object:clsid() end
function game_object:id() end
function game_object:story_id() end
function game_object:section() end
function game_object:name() end
function game_object:parent() end
function game_object:mass() end
function game_object:cost() end
function game_object:condition() end
function game_object:set_condition() end
function game_object:power_critical() end
function game_object:psy_factor() end
function game_object:set_psy_factor() end
function game_object:is_device_enabled() end
function game_object:set_device_enabled() end
function game_object:death_time() end
function game_object:armor() end
function game_object:max_health() end
function game_object:accuracy() end
function game_object:alive() end
function game_object:team() end
function game_object:squad() end
function game_object:group() end
function game_object:change_team() end
function game_object:set_visual_memory_enabled() end
function game_object:kill() end
function game_object:hit() end
function game_object:play_cycle() end
function game_object:play_cycle() end
function game_object:fov() end
function game_object:range() end
function game_object:relation() end
function game_object:script() end
function game_object:get_script() end
function game_object:get_script_name() end
function game_object:reset_action_queue() end
function game_object:see() end
function game_object:see() end
function game_object:who_hit_name() end
function game_object:who_hit_section_name() end
function game_object:rank() end
function game_object:command() end
function game_object:action() end
function game_object:object_count() end
function game_object:object() end
function game_object:object() end
function game_object:object_id() end
function game_object:active_item() end
function game_object:set_callback() end
function game_object:set_callback() end
function game_object:set_callback() end
function game_object:set_patrol_extrapolate_callback() end
function game_object:set_patrol_extrapolate_callback() end
function game_object:set_patrol_extrapolate_callback() end
function game_object:set_enemy_callback() end
function game_object:set_enemy_callback() end
function game_object:set_enemy_callback() end
function game_object:patrol() end
function game_object:get_ammo_in_magazine() end
function game_object:get_ammo_total() end
function game_object:set_ammo_elapsed() end
function game_object:use() end
function game_object:start_trade() end
function game_object:start_upgrade() end
function game_object:set_ammo_type() end
function game_object:get_ammo_type() end
function game_object:get_ammo_count_for_type() end
function game_object:get_main_weapon_type() end
function game_object:get_weapon_type() end
function game_object:set_main_weapon_type() end
function game_object:set_weapon_type() end
function game_object:has_ammo_type() end
function game_object:get_weapon_substate() end
function game_object:set_weight() end
function game_object:set_queue_size() end
function game_object:best_hit() end
function game_object:best_sound() end
function game_object:best_danger() end
function game_object:best_enemy() end
function game_object:best_item() end
function game_object:action_count() end
function game_object:action_by_index() end
function game_object:set_hear_callback() end
function game_object:set_hear_callback() end
function game_object:clear_hear_callback() end
function game_object:memory_time() end
function game_object:memory_position() end
function game_object:best_weapon() end
function game_object:explode() end
function game_object:get_enemy() end
function game_object:get_corpse() end
function game_object:get_enemy_strength() end
function game_object:get_sound_info() end
function game_object:get_monster_hit_info() end
function game_object:bind_object() end
function game_object:motivation_action_manager() end
function game_object:set_force_anti_aim() end
function game_object:get_force_anti_aim() end
function game_object:set_override_animation() end
function game_object:set_override_animation() end
function game_object:clear_override_animation() end
function game_object:burer_set_force_gravi_attack() end
function game_object:burer_get_force_gravi_attack() end
function game_object:poltergeist_set_actor_ignore() end
function game_object:poltergeist_get_actor_ignore() end
function game_object:force_visibility_state() end
function game_object:get_visibility_state() end
function game_object:force_stand_sleep_animation() end
function game_object:release_stand_sleep_animation() end
function game_object:set_invisible() end
function game_object:set_manual_invisibility() end
function game_object:set_alien_control() end
function game_object:set_enemy() end
function game_object:set_vis_state() end
function game_object:set_collision_off() end
function game_object:set_capture_anim() end
function game_object:fake_death_fall_down() end
function game_object:fake_death_stand_up() end
function game_object:skip_transfer_enemy() end
function game_object:set_home() end
function game_object:set_home() end
function game_object:remove_home() end
function game_object:berserk() end
function game_object:can_script_capture() end
function game_object:set_custom_panic_threshold() end
function game_object:set_default_panic_threshold() end
function game_object:get_current_outfit() end
function game_object:get_current_outfit_protection() end
function game_object:deadbody_closed() end
function game_object:deadbody_closed_status() end
function game_object:deadbody_can_take() end
function game_object:deadbody_can_take_status() end
function game_object:can_select_weapon() end
function game_object:can_select_weapon() end
function game_object:get_current_direction() end
function game_object:set_body_state() end
function game_object:set_movement_type() end
function game_object:set_mental_state() end
function game_object:set_path_type() end
function game_object:set_detail_path_type() end
function game_object:body_state() end
function game_object:target_body_state() end
function game_object:movement_type() end
function game_object:target_movement_type() end
function game_object:mental_state() end
function game_object:target_mental_state() end
function game_object:path_type() end
function game_object:detail_path_type() end
function game_object:set_desired_position() end
function game_object:set_desired_position() end
function game_object:set_desired_direction() end
function game_object:set_desired_direction() end
function game_object:set_patrol_path() end
function game_object:inactualize_patrol_path() end
function game_object:set_dest_level_vertex_id() end
function game_object:set_dest_game_vertex_id() end
function game_object:set_movement_selection_type() end
function game_object:level_vertex_id() end
function game_object:game_vertex_id() end
function game_object:add_animation() end
function game_object:add_animation() end
function game_object:clear_animations() end
function game_object:animation_count() end
function game_object:animation_slot() end
function game_object:ignore_monster_threshold() end
function game_object:restore_ignore_monster_threshold() end
function game_object:ignore_monster_threshold() end
function game_object:max_ignore_monster_distance() end
function game_object:restore_max_ignore_monster_distance() end
function game_object:max_ignore_monster_distance() end
function game_object:eat() end
function game_object:extrapolate_length() end
function game_object:extrapolate_length() end
function game_object:set_fov() end
function game_object:set_range() end
function game_object:head_orientation() end
function game_object:set_actor_position() end
function game_object:set_actor_direction() end
function game_object:set_actor_direction() end
function game_object:set_actor_direction() end
function game_object:set_actor_direction() end
function game_object:disable_hit_marks() end
function game_object:disable_hit_marks() end
function game_object:get_movement_speed() end
function game_object:set_movement_speed() end
function game_object:set_npc_position() end
function game_object:vertex_in_direction() end
function game_object:item_in_slot() end
function game_object:active_detector() end
function game_object:hide_detector() end
function game_object:force_hide_detector() end
function game_object:show_detector() end
function game_object:active_slot() end
function game_object:activate_slot() end
function game_object:debug_planner() end
function game_object:invulnerable() end
function game_object:invulnerable() end
function game_object:get_smart_cover_description() end
function game_object:set_visual_name() end
function game_object:get_inv_weight() end
function game_object:get_inv_max_weight() end
function game_object:get_visual_name() end
function game_object:can_throw_grenades() end
function game_object:can_throw_grenades() end
function game_object:group_throw_time_interval() end
function game_object:group_throw_time_interval() end
function game_object:register_in_combat() end
function game_object:unregister_in_combat() end
function game_object:find_best_cover() end
function game_object:use_smart_covers_only() end
function game_object:use_smart_covers_only() end
function game_object:in_smart_cover() end
function game_object:set_dest_smart_cover() end
function game_object:set_dest_smart_cover() end
function game_object:get_dest_smart_cover() end
function game_object:get_dest_smart_cover_name() end
function game_object:set_dest_loophole() end
function game_object:set_dest_loophole() end
function game_object:set_smart_cover_target() end
function game_object:set_smart_cover_target() end
function game_object:set_smart_cover_target() end
function game_object:set_smart_cover_target_selector() end
function game_object:set_smart_cover_target_selector() end
function game_object:set_smart_cover_target_selector() end
function game_object:set_smart_cover_target_idle() end
function game_object:set_smart_cover_target_lookout() end
function game_object:set_smart_cover_target_fire() end
function game_object:set_smart_cover_target_fire_no_lookout() end
function game_object:set_smart_cover_target_idle() end
function game_object:set_smart_cover_target_default() end
function game_object:idle_min_time() end
function game_object:idle_min_time() end
function game_object:idle_max_time() end
function game_object:idle_max_time() end
function game_object:lookout_min_time() end
function game_object:lookout_min_time() end
function game_object:lookout_max_time() end
function game_object:lookout_max_time() end
function game_object:in_loophole_fov() end
function game_object:in_current_loophole_fov() end
function game_object:in_loophole_range() end
function game_object:in_current_loophole_range() end
function game_object:apply_loophole_direction_distance() end
function game_object:apply_loophole_direction_distance() end
function game_object:movement_target_reached() end
function game_object:suitable_smart_cover() end
function game_object:take_items_enabled() end
function game_object:take_items_enabled() end
function game_object:death_sound_enabled() end
function game_object:death_sound_enabled() end
function game_object:register_door_for_npc() end
function game_object:unregister_door_for_npc() end
function game_object:on_door_is_open() end
function game_object:on_door_is_closed() end
function game_object:lock_door_for_npc() end
function game_object:unlock_door_for_npc() end
function game_object:is_door_locked_for_npc() end
function game_object:is_door_blocked_by_npc() end
function game_object:is_weapon_going_to_be_strapped() end
function game_object:reload_weapon() end

-- Following method are defined here: src\xrGame\script_game_object_script3.cpp
function game_object:add_sound() end
function game_object:add_sound() end
function game_object:add_combat_sound() end
function game_object:remove_sound() end
function game_object:set_sound_mask() end
function game_object:play_sound() end
function game_object:play_sound() end
function game_object:play_sound() end
function game_object:play_sound() end
function game_object:play_sound() end
function game_object:play_sound() end
function game_object:binded_object() end
function game_object:set_previous_point() end
function game_object:set_start_point() end
function game_object:get_current_point_index() end
function game_object:path_completed() end
function game_object:patrol_path_make_inactual() end
function game_object:enable_memory_object() end
function game_object:active_sound_count() end
function game_object:active_sound_count() end
function game_object:best_cover() end
function game_object:safe_cover() end
function game_object:spawn_ini() end
function game_object:memory_remove_links() end
function game_object:memory_visible_objects() end
function game_object:memory_sound_objects() end
function game_object:memory_hit_objects() end
function game_object:not_yet_visible_objects() end
function game_object:visibility_threshold() end
function game_object:enable_vision() end
function game_object:vision_enabled() end
function game_object:set_sound_threshold() end
function game_object:restore_sound_threshold() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_sight() end
function game_object:set_item() end
function game_object:set_item() end
function game_object:set_item() end
function game_object:set_item() end
function game_object:is_body_turning() end
function game_object:get_bone_id() end
function game_object:get_bone_id() end
function game_object:bone_id() end
function game_object:bone_id() end
function game_object:bone_name() end
function game_object:bone_name() end
function game_object:bone_position() end
function game_object:bone_position() end
function game_object:bone_position() end
function game_object:bone_position() end
function game_object:bone_direction() end
function game_object:bone_direction() end
function game_object:bone_direction() end
function game_object:bone_direction() end
function game_object:bone_transform() end
function game_object:bone_transform() end
function game_object:bone_transform() end
function game_object:bone_transform() end
function game_object:bone_parent() end
function game_object:bone_parent() end
function game_object:bone_parent() end
function game_object:bone_parent() end
function game_object:bone_visible() end
function game_object:bone_visible() end
function game_object:bone_visible() end
function game_object:bone_visible() end
function game_object:set_bone_visible() end
function game_object:set_bone_visible() end
function game_object:set_bone_visible() end
function game_object:set_bone_visible() end
function game_object:list_bones() end
function game_object:add_restrictions() end
function game_object:remove_restrictions() end
function game_object:remove_all_restrictions() end
function game_object:in_restrictions() end
function game_object:out_restrictions() end
function game_object:base_in_restrictions() end
function game_object:base_out_restrictions() end
function game_object:accessible() end
function game_object:accessible() end
function game_object:accessible_nearest() end
function game_object:enable_attachable_item() end
function game_object:attachable_item_enabled() end
function game_object:night_vision_allowed() end
function game_object:enable_night_vision() end
function game_object:night_vision_enabled() end
function game_object:enable_torch() end
function game_object:torch_enabled() end
function game_object:attachable_item_load_attach() end
function game_object:update_torch() end
function game_object:weapon_strapped() end
function game_object:weapon_unstrapped() end
function game_object:EPdaMsg() end
function game_object:dialog_pda_msg() end
function game_object:info_pda_msg() end
function game_object:no_pda_msg() end
function game_object:give_info_portion() end
function game_object:disable_info_portion() end
function game_object:give_game_news() end
function game_object:give_game_news() end
function game_object:give_talk_message() end
function game_object:give_talk_message2() end
function game_object:has_info() end
function game_object:dont_has_info() end
function game_object:get_task_state() end
function game_object:set_task_state() end
function game_object:give_task() end
function game_object:set_active_task() end
function game_object:is_active_task() end
function game_object:get_task() end
function game_object:is_talking() end
function game_object:stop_talk() end
function game_object:enable_talk() end
function game_object:disable_talk() end
function game_object:is_talk_enabled() end
function game_object:enable_trade() end
function game_object:disable_trade() end
function game_object:is_trade_enabled() end
function game_object:enable_inv_upgrade() end
function game_object:disable_inv_upgrade() end
function game_object:is_inv_upgrade_enabled() end
function game_object:disable_show_hide_sounds() end
function game_object:inventory_for_each() end
function game_object:drop_item() end
function game_object:drop_item_and_teleport() end
function game_object:transfer_item() end
function game_object:take_item() end
function game_object:transfer_money() end
function game_object:give_money() end
function game_object:money() end
function game_object:iterate_inventory() end
function game_object:iterate_ruck() end
function game_object:iterate_belt() end
function game_object:iterate_inventory_box() end
function game_object:make_item_active() end
function game_object:move_to_ruck() end
function game_object:move_to_slot() end
function game_object:move_to_belt() end
function game_object:is_on_belt() end
function game_object:item_on_belt() end
function game_object:belt_count() end
function game_object:item_allow_trade() end
function game_object:item_deny_trade() end
function game_object:switch_to_trade() end
function game_object:switch_to_upgrade() end
function game_object:switch_to_talk() end
function game_object:run_talk_dialog() end
function game_object:allow_break_talk_dialog() end
function game_object:hide_weapon() end
function game_object:restore_weapon() end
function game_object:weapon_is_grenadelauncher() end
function game_object:weapon_is_scope() end
function game_object:weapon_is_silencer() end
function game_object:weapon_grenadelauncher_status() end
function game_object:weapon_scope_status() end
function game_object:weapon_silencer_status() end
function game_object:allow_sprint() end
function game_object:set_start_dialog() end
function game_object:get_start_dialog() end
function game_object:restore_default_start_dialog() end
function game_object:goodwill() end
function game_object:set_goodwill() end
function game_object:force_set_goodwill() end
function game_object:change_goodwill() end
function game_object:general_goodwill() end
function game_object:set_relation() end
function game_object:community_goodwill() end
function game_object:set_community_goodwill() end
function game_object:sympathy() end
function game_object:set_sympathy() end
function game_object:profile_name() end
function game_object:character_name() end
function game_object:character_icon() end
function game_object:character_rank() end
function game_object:character_dialogs() end
function game_object:set_character_rank() end
function game_object:change_character_rank() end
function game_object:character_reputation() end
function game_object:set_character_reputation() end
function game_object:change_character_reputation() end
function game_object:character_community() end
function game_object:set_character_community() end
function game_object:get_actor_relation_flags() end
function game_object:set_actor_relation_flags() end
function game_object:sound_voice_prefix() end
function game_object:ACTOR_RELATIONS() end
function game_object:relation_attack() end
function game_object:relation_fight_help_monster() end
function game_object:relation_fight_help_human() end
function game_object:relation_kill() end
function game_object:CLSIDS() end
function game_object:no_pda_msg() end
function game_object:set_restrictor_type() end
function game_object:get_restrictor_type() end
function game_object:enable_anomaly() end
function game_object:disable_anomaly() end
function game_object:set_idle_particles() end
function game_object:get_anomaly_power() end
function game_object:set_anomaly_power() end
function game_object:get_anomaly_radius() end
function game_object:set_anomaly_radius() end
function game_object:set_anomaly_position() end
function game_object:get_artefact_health() end
function game_object:get_artefact_radiation() end
function game_object:get_artefact_satiety() end
function game_object:get_artefact_power() end
function game_object:get_artefact_bleeding() end
function game_object:get_artefact_immunity() end
function game_object:get_artefact_additional_inventory_weight() end
function game_object:set_artefact_health() end
function game_object:set_artefact_radiation() end
function game_object:set_artefact_satiety() end
function game_object:set_artefact_power() end
function game_object:set_artefact_bleeding() end
function game_object:set_artefact_immunity() end
function game_object:set_artefact_additional_inventory_weight() end
function game_object:get_helicopter() end
function game_object:get_car() end
function game_object:get_stmgun() end
function game_object:get_projector() end
function game_object:get_hanging_lamp() end
function game_object:get_physics_shell() end
function game_object:get_holder_class() end
function game_object:get_current_holder() end
function game_object:set_tip_text() end
function game_object:set_tip_text_default() end
function game_object:set_nonscript_usable() end
function game_object:active_zone_contact() end
function game_object:inside() end
function game_object:inside() end
function game_object:set_fastcall() end
function game_object:set_const_force() end
function game_object:info_add() end
function game_object:info_clear() end
function game_object:is_inv_box_empty() end
function game_object:inv_box_closed() end
function game_object:inv_box_closed_status() end
function game_object:inv_box_can_take() end
function game_object:inv_box_can_take_status() end
function game_object:jump() end
function game_object:make_object_visible_somewhen() end
function game_object:buy_condition() end
function game_object:buy_condition() end
function game_object:show_condition() end
function game_object:sell_condition() end
function game_object:sell_condition() end
function game_object:buy_supplies() end
function game_object:buy_item_condition_factor() end
function game_object:buy_item_exponent() end
function game_object:sell_item_exponent() end
function game_object:sound_prefix() end
function game_object:sound_prefix() end
function game_object:location_on_path() end
function game_object:is_there_items_to_pickup() end
function game_object:wounded() end
function game_object:wounded() end
function game_object:set_enable_movement_collision() end
function game_object:mark_item_dropped() end
function game_object:marked_dropped() end
function game_object:unload_magazine() end
function game_object:force_unload_magazine() end
function game_object:sight_params() end
function game_object:movement_enabled() end
function game_object:movement_enabled() end
function game_object:critically_wounded() end
function game_object:get_campfire() end
function game_object:get_artefact() end
function game_object:get_physics_object() end
function game_object:aim_time() end
function game_object:aim_time() end
function game_object:special_danger_move() end
function game_object:special_danger_move() end
function game_object:sniper_update_rate() end
function game_object:sniper_update_rate() end
function game_object:sniper_fire_mode() end
function game_object:sniper_fire_mode() end
function game_object:aim_bone_id() end
function game_object:aim_bone_id() end
function game_object:actor_look_at_point() end
function game_object:actor_stop_look_at_point() end
function game_object:enable_level_changer() end
function game_object:is_level_changer_enabled() end
function game_object:set_level_changer_invitation() end
function game_object:start_particles() end
function game_object:stop_particles() end
function game_object:attach_vehicle() end
function game_object:detach_vehicle() end
function game_object:get_attached_vehicle() end
function game_object:reset_bone_protections() end
function game_object:iterate_feel_touch() end
function game_object:get_luminocity_hemi() end
function game_object:get_luminocity() end
function game_object:set_health_ex() end
function game_object:force_set_position() end
function game_object:force_set_angle() end
function game_object:angle() end
function game_object:force_set_rotation() end
function game_object:set_spatial_type() end
function game_object:get_spatial_type() end
function game_object:destroy_object() end
function game_object:ammo_get_count() end
function game_object:ammo_set_count() end
function game_object:ammo_box_size() end
function game_object:weapon_addon_attach() end
function game_object:weapon_addon_detach() end
function game_object:install_upgrade() end
function game_object:has_upgrade() end
function game_object:iterate_installed_upgrades() end
function game_object:weapon_in_grenade_mode() end
function game_object:play_hud_motion() end
function game_object:switch_state() end
function game_object:get_state() end
function game_object:set_remaining_uses() end
function game_object:get_remaining_uses() end
function game_object:get_max_uses() end
function game_object:phantom_set_enemy() end
function game_object:set_character_icon() end
function game_object:cast_Actor() end
function game_object:cast_Car() end
function game_object:cast_Heli() end
function game_object:cast_InventoryOwner() end
function game_object:cast_InventoryBox() end
function game_object:cast_CustomZone() end
function game_object:cast_TorridZone() end
function game_object:cast_MosquitoBald() end
function game_object:cast_ZoneCampfire() end
function game_object:cast_InventoryItem() end
function game_object:cast_CustomOutfit() end
function game_object:cast_Helmet() end
function game_object:cast_Artefact() end
function game_object:cast_Ammo() end
function game_object:cast_Weapon() end
function game_object:cast_Knife() end
function game_object:cast_WeaponMagazined() end
function game_object:cast_WeaponMagazinedWGrenade() end
function game_object:cast_EatableItem() end
function game_object:cast_Medkit() end
function game_object:cast_Antirad() end
function game_object:cast_FoodItem() end
function game_object:cast_BottleItem() end
function game_object:cast_Missile() end
function game_object:cast_Explosive() end
function game_object:set_color_animator() end
function game_object:reset_color_animator() end
function game_object:is_game_object() end
function game_object:is_car() end
function game_object:is_helicopter() end
function game_object:is_holder() end
function game_object:is_entity_alive() end
function game_object:is_inventory_item() end
function game_object:is_inventory_owner() end
function game_object:is_actor() end
function game_object:is_custom_monster() end
function game_object:is_weapon() end
function game_object:is_medkit() end
function game_object:is_eatable_item() end
function game_object:is_antirad() end
function game_object:is_outfit() end
function game_object:is_helmet() end
function game_object:is_scope() end
function game_object:is_silencer() end
function game_object:is_grenade_launcher() end
function game_object:is_weapon_magazined() end
function game_object:is_space_restrictor() end
function game_object:is_stalker() end
function game_object:is_anomaly() end
function game_object:is_monster() end
function game_object:is_explosive() end
function game_object:is_script_zone() end
function game_object:is_projector() end
function game_object:is_trader() end
function game_object:is_hud_item() end
function game_object:is_food_item() end
function game_object:is_artefact() end
function game_object:is_ammo() end
function game_object:is_missile() end
function game_object:is_physics_shell_holder() end
function game_object:is_grenade() end
function game_object:is_bottle_item() end
function game_object:is_torch() end
function game_object:is_weapon_gl() end
function game_object:is_inventory_box() end
function game_object:get_actor_max_weight() end
function game_object:set_actor_max_weight() end
function game_object:get_actor_max_walk_weight() end
function game_object:set_actor_max_walk_weight() end
function game_object:get_additional_max_weight() end
function game_object:set_additional_max_weight() end
function game_object:get_additional_max_walk_weight() end
function game_object:set_additional_max_walk_weight() end
function game_object:get_total_weight() end
function game_object:update_weight() end
function game_object:get_total_weight_force_update() end
function game_object:get_actor_ui_luminosity() end
function game_object:weight() end
function game_object:get_actor_jump_speed() end
function game_object:set_actor_jump_speed() end
function game_object:get_actor_sprint_koef() end
function game_object:set_actor_sprint_koef() end
function game_object:get_actor_run_coef() end
function game_object:set_actor_run_coef() end
function game_object:get_actor_runback_coef() end
function game_object:set_actor_runback_coef() end
function game_object:get_actor_walk_accel() end
function game_object:set_actor_walk_accel() end
function game_object:set_actor_box_y_offset() end
function game_object:get_actor_walk_back_coef() end
function game_object:set_actor_walk_back_coef() end
function game_object:get_actor_crouch_coef() end
function game_object:set_actor_crouch_coef() end
function game_object:get_actor_climb_coef() end
function game_object:set_actor_climb_coef() end
function game_object:get_actor_walk_strafe_coef() end
function game_object:set_actor_walk_strafe_coef() end
function game_object:get_actor_run_strafe_coef() end
function game_object:set_actor_run_strafe_coef() end
function game_object:get_actor_sprint_strafe_coef() end
function game_object:set_actor_sprint_strafe_coef() end
function game_object:get_actor_object_looking_at() end
function game_object:get_actor_person_looking_at() end
function game_object:get_actor_default_action_for_object() end
function game_object:get_actor_lookout_coef() end
function game_object:set_actor_lookout_coef() end
function game_object:get_enable_anomalies_pathfinding() end
function game_object:set_enable_anomalies_pathfinding() end
function game_object:get_enable_anomalies_damage() end
function game_object:set_enable_anomalies_damage() end
function game_object:get_talking_npc() end
function game_object:get_scope_ui() end
function game_object:set_scope_ui() end
function game_object:set_can_be_harmed() end
function game_object:can_be_harmed() end
function game_object:add_attachment() end
function game_object:get_attachment() end
function game_object:remove_attachment() end
function game_object:remove_attachment() end
function game_object:iterate_attachments() end
function game_object:get_shaders() end
function game_object:get_default_shaders() end
function game_object:set_shader() end
function game_object:reset_shader() end

---@enum game_object.relation
game_object.relation = {}

---@enum game_object.action_types
game_object.action_types = {}

---@enum game_object.EPathType
game_object.EPathType = {
    game_path = 0,
    level_path = 1,
    patrol_path = 2,
    no_path = 3,
}

---@enum game_object.ESelectionType
game_object.ESelectionType = {}

---@class callback
callback = {}

---@enum callback.callback_types
callback.callback_types = {}

function buy_condition() end
function buy_condition() end
function sell_condition() end
function sell_condition() end
function show_condition() end
