---@meta

---@enum EUIMessages
EUIMessages = {
	WINDOW_LBUTTON_DOWN = 0,
	WINDOW_RBUTTON_DOWN = 1,
	WINDOW_CBUTTON_DOWN = 2,

	WINDOW_LBUTTON_UP = 3,
	WINDOW_RBUTTON_UP = 4,
	WINDOW_CBUTTON_UP = 5,

	WINDOW_MOUSE_MOVE = 6,
	WINDOW_MOUSE_WHEEL_UP = 7,
	WINDOW_MOUSE_WHEEL_DOWN = 8,
	WINDOW_LBUTTON_DB_CLICK = 9,
	WINDOW_KEY_PRESSED = 10,
	WINDOW_KEY_RELEASED = 11,
	WINDOW_KEY_HOLD = 12,
	WINDOW_MOUSE_CAPTURE_LOST = 13,
	WINDOW_KEYBOARD_CAPTURE_LOST = 14,

	WINDOW_FOCUS_RECEIVED = 15,
	WINDOW_FOCUS_LOST = 16,

	BUTTON_CLICKED = 17,
	BUTTON_DOWN = 18,

	TAB_CHANGED = 19,

	CHECK_BUTTON_SET = 20,
	CHECK_BUTTON_RESET = 21,

	RADIOBUTTON_SET = 22,

	DRAG_DROP_ITEM_DRAG = 23,
	DRAG_DROP_ITEM_DROP = 24,
	DRAG_DROP_ITEM_DB_CLICK = 25,
	DRAG_DROP_ITEM_LBUTTON_CLICK = 26,
	DRAG_DROP_ITEM_RBUTTON_CLICK = 27,
	DRAG_DROP_ITEM_SELECTED = 28,
	DRAG_DROP_ITEM_FOCUSED_UPDATE = 29,

	SCROLLBOX_MOVE = 30,

	SCROLLBAR_VSCROLL = 31,
	SCROLLBAR_HSCROLL = 32,
	SCROLLBAR_NEEDUPDATE = 33,

	CHILD_CHANGED_SIZE = 34,

	LIST_ITEM_CLICKED = 35,
	LIST_ITEM_SELECT = 36,
	LIST_ITEM_FOCUS_RECEIVED = 37,

	PROPERTY_CLICKED = 38,

	MESSAGE_BOX_OK_CLICKED = 39,
	MESSAGE_BOX_YES_CLICKED = 40,
	MESSAGE_BOX_QUIT_WIN_CLICKED = 41,
	MESSAGE_BOX_QUIT_GAME_CLICKED = 42,
	MESSAGE_BOX_NO_CLICKED = 43,
	MESSAGE_BOX_CANCEL_CLICKED = 44,
	MESSAGE_BOX_COPY_CLICKED = 45,

	TALK_DIALOG_TRADE_BUTTON_CLICKED = 46,
	TALK_DIALOG_UPGRADE_BUTTON_CLICKED = 47,
	TALK_DIALOG_QUESTION_CLICKED = 48,

	PDA_TASK_SET_TARGET_MAP = 49,
	PDA_TASK_SHOW_MAP_SPOT = 50,
	PDA_TASK_HIDE_MAP_SPOT = 51,
	PDA_TASK_SHOW_HINT = 52,
	PDA_TASK_HIDE_HINT = 53,

	INVENTORY_DROP_ACTION = 54,
	INVENTORY_EAT_ACTION = 55,
	INVENTORY_EAT2_ACTION = 56,
	INVENTORY_EAT3_ACTION = 57,
	INVENTORY_EAT4_ACTION = 58,
	INVENTORY_EAT5_ACTION = 59,
	INVENTORY_EAT6_ACTION = 60,
	INVENTORY_EAT7_ACTION = 61,
	INVENTORY_EAT8_ACTION = 62,
	INVENTORY_EAT9_ACTION = 63,
	INVENTORY_EAT10_ACTION = 64,
	INVENTORY_EAT11_ACTION = 65,
	INVENTORY_DONATE_ACTION = 66,
	INVENTORY_PLAY_ACTION = 67,
	INVENTORY_TO_BELT_ACTION = 68,
	INVENTORY_TO_SLOT_ACTION = 69,
	INVENTORY_TO_BAG_ACTION = 70,
	INVENTORY_ATTACH_ADDON = 71,
	INVENTORY_REPAIR = 72,

	INVENTORY_ATTACH_SCOPE_ADDON = 73,
	INVENTORY_DETACH_SCOPE_ADDON = 74,

	INVENTORY_ATTACH_SILENCER_ADDON = 75,
	INVENTORY_DETACH_SILENCER_ADDON = 76,

	INVENTORY_ATTACH_GRENADE_LAUNCHER_ADDON = 77,
	INVENTORY_DETACH_GRENADE_LAUNCHER_ADDON = 78,

	INVENTORY_RELOAD_MAGAZINE = 79,
	INVENTORY_UNLOAD_MAGAZINE = 80,
	INVENTORY_SELL_ITEM = 81,

	EDIT_TEXT_COMMIT = 82,
	EDIT_TEXT_CANCEL = 83,
	MAP_SHOW_HINT = 84,
	MAP_HIDE_HINT = 85,
	MAP_SELECT_SPOT = 86,

	MAIN_MENU_RELOADED = 87,
	MAP_SELECT_SPOT2 = 88

}

---@Class CUIScriptWnd
CUIScriptWnd = {}

---OnKeyboard Callback
---@param dik number
---@param keyboard_action EUIMessages
---@return boolean
function CUIScriptWnd:OnKeyboard(dik, keyboard_action) end

---Update Window
function CUIScriptWnd:Update() end

---Dispatch
---@param cmd number
---@param param number
---@return boolean
function CUIScriptWnd:Dispatch(cmd, param) end

---Load
---@param xml_name string
---@return boolean
function CUIScriptWnd:Load(xml_name) end

---Adding a callback
---@param control_id string
---@param evt number
---@param functor fun(arg: any)
---@param object any
function CUIScriptWnd:AddCallback(control_id, evt, functor, object) end

---Register
---@param name string
function CUIScriptWnd:Register(name) end

