on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: 'Building, basic UTest and memcheck tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install cmake valgrind
      - name: Building
        run: cmake -B out/ -DENABLE_DLTX_TRACE=ON && cmake --build out/
      - name: Test simple.ltx
        run: .github/scripts/basic-utest.sh simple.ltx
      - name: Test dirty.ltx
        run: .github/scripts/basic-utest.sh dirty.ltx
      - name: Test case.ltx
        run: .github/scripts/basic-utest.sh case.ltx
      - name: Test inheritance.ltx
        run: .github/scripts/basic-utest.sh inheritance.ltx
      - name: Test override.ltx
        run: .github/scripts/basic-utest.sh override.ltx
      - name: Test override-first.ltx
        run: .github/scripts/basic-utest.sh override-first.ltx
      - name: Test override-safe.ltx
        run: .github/scripts/basic-utest.sh override-safe.ltx
      - name: Test deletion.ltx
        run: .github/scripts/basic-utest.sh deletion.ltx
      - name: Test glob.ltx
        run: .github/scripts/basic-utest.sh glob.ltx
