on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: 'Building, basic UTest and memcheck tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install valgrind
      - name: Building
        run: ./build.sh
      - name: Test simple.ltx
        run: .github/scripts/basic-utest.sh simple.ltx 299566254b1f130dee3e385c193db85d
      - name: Test dirty.ltx
        run: .github/scripts/basic-utest.sh dirty.ltx 7ebf76cc81f489a9dcf3ba25d511e521
      - name: Test case.ltx
        run: .github/scripts/basic-utest.sh case.ltx 2436af88a64fa273ac4d531e43d0637a
      - name: Test inheritance.ltx
        run: .github/scripts/basic-utest.sh inheritance.ltx 2f8645e91e0b0788994c4df376d020e3
      - name: Test override.ltx
        run: .github/scripts/basic-utest.sh override.ltx 885ebd029102b01ad15fd3fea671e61d
      - name: Test override-first.ltx
        run: .github/scripts/basic-utest.sh override-first.ltx 5b6c3244fa22ee968deda055ca415376
      - name: Test override-safe.ltx
        run: .github/scripts/basic-utest.sh override-safe.ltx c9b6d91ab0b4960f7e612ce8d972ae82
      - name: Test deletion.ltx
        run: .github/scripts/basic-utest.sh deletion.ltx 48810c0b253e184c644f52c98afb98de
      - name: Test glob.ltx
        run: .github/scripts/basic-utest.sh glob.ltx d93930a3f1185173639710ba7a17cf1c
