# More in here: https://www.msys2.org/docs/ci/

name: MSYS2
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: cmake gcc git make
      - name: CI-Build
        run: |
          cmake -B out/ -DENABLE_DLTX_TRACE=ON && cmake --build out/
          NO_VALGRIND=y .github/scripts/basic-utest.sh
